repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        # Explicitly specify C++ files else,
        # `Configuration file(s) do(es) not support Json` error occurs
        files: \.(cpp|h|inl)$
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: ["gitpython>=3.1.24"]
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

exclude: ^External/
